### ISSUE TITLE
Don't accept `undefined` as a valid css value

### ISSUE THREAD

**Issue by casperin** [casperin/bem-css#2]
I don't want to see this in my css... ever
```css
.foo {
  color: undefined;
}
```
