### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by casperin** [casperin/bem-css#6]
We need a way to add media queries. Maybe
```js
// foo.js
block(
  [ color("red") ],
  media("screen and (max-width: 992px)", [
    color("blue")
  ]
)
```
Would become
```css
.foo {
  color: red;
}
@media screen and (max-width: 992px) {
  .foo {
    color: blue;
  }
}
```
